"""initial_schema

Revision ID: 0441ad7dc315
Revises: 
Create Date: 2026-05-01 00:53:46.273291
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0441ad7dc315'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
