"""vendor_portal

Revision ID: 634b0222b6dd
Revises: 0441ad7dc315
Create Date: 2026-05-01 01:14:53.828442
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '634b0222b6dd'
down_revision: Union[str, None] = '0441ad7dc315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add 'vendor' value to the existing user_role enum
    op.execute("ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'vendor' BEFORE 'admin'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('business_email', sa.String(length=255), nullable=False),
    sa.Column('business_phone', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('business_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('warehouse_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bank_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'suspended', 'rejected', name='vendor_status'), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_business_email'), 'vendors', ['business_email'], unique=True)
    op.create_index(op.f('ix_vendors_id'), 'vendors', ['id'], unique=False)
    op.create_index(op.f('ix_vendors_status'), 'vendors', ['status'], unique=False)
    op.create_table('payouts',
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('deductions', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'paid', 'failed', name='payout_status'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payouts_id'), 'payouts', ['id'], unique=False)
    op.create_index(op.f('ix_payouts_status'), 'payouts', ['status'], unique=False)
    op.create_index(op.f('ix_payouts_vendor_id'), 'payouts', ['vendor_id'], unique=False)
    op.create_table('vendor_documents',
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('business_license', 'tax_id', 'bank_statement', 'id_proof', 'other', name='document_type'), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='document_status'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_documents_id'), 'vendor_documents', ['id'], unique=False)
    op.create_index(op.f('ix_vendor_documents_vendor_id'), 'vendor_documents', ['vendor_id'], unique=False)
    op.create_table('vendor_users',
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'staff', name='vendor_user_role'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id', 'user_id', name='uq_vendor_user')
    )
    op.create_index(op.f('ix_vendor_users_id'), 'vendor_users', ['id'], unique=False)
    op.create_index(op.f('ix_vendor_users_user_id'), 'vendor_users', ['user_id'], unique=False)
    op.create_index(op.f('ix_vendor_users_vendor_id'), 'vendor_users', ['vendor_id'], unique=False)
    op.create_table('inventory_logs',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('change_quantity', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('sale', 'restock', 'adjustment', 'return_', 'reservation', 'cancellation', name='inventory_change_reason'), nullable=False),
    sa.Column('previous_stock', sa.Integer(), nullable=False),
    sa.Column('new_stock', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_logs_id'), 'inventory_logs', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_logs_product_id'), 'inventory_logs', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_logs_vendor_id'), 'inventory_logs', ['vendor_id'], unique=False)
    op.create_table('vendor_orders',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('new', 'sent_to_vendor', 'vendor_accepted', 'processing', 'shipped', 'delivered', 'cancelled', name='vendor_order_status'), nullable=False),
    sa.Column('wholesale_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('platform_margin', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vendor_notes', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('payout_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payout_id'], ['payouts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_orders_id'), 'vendor_orders', ['id'], unique=False)
    op.create_index(op.f('ix_vendor_orders_order_id'), 'vendor_orders', ['order_id'], unique=False)
    op.create_index(op.f('ix_vendor_orders_payout_id'), 'vendor_orders', ['payout_id'], unique=False)
    op.create_index(op.f('ix_vendor_orders_status'), 'vendor_orders', ['status'], unique=False)
    op.create_index(op.f('ix_vendor_orders_vendor_id'), 'vendor_orders', ['vendor_id'], unique=False)
    op.create_table('shipments',
    sa.Column('vendor_order_id', sa.UUID(), nullable=False),
    sa.Column('carrier_name', sa.String(length=100), nullable=False),
    sa.Column('tracking_number', sa.String(length=200), nullable=False),
    sa.Column('estimated_delivery_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_order_id'], ['vendor_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_order_id')
    )
    op.create_index(op.f('ix_shipments_id'), 'shipments', ['id'], unique=False)
    op.add_column('order_items', sa.Column('vendor_id', sa.UUID(), nullable=True))
    op.add_column('order_items', sa.Column('wholesale_price_snapshot', sa.Numeric(precision=12, scale=2), nullable=True))
    op.create_index(op.f('ix_order_items_vendor_id'), 'order_items', ['vendor_id'], unique=False)
    op.create_foreign_key(None, 'order_items', 'vendors', ['vendor_id'], ['id'], ondelete='SET NULL')
    op.add_column('products', sa.Column('vendor_id', sa.UUID(), nullable=True))
    op.add_column('products', sa.Column('wholesale_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('products', sa.Column('is_approved', sa.Boolean(), nullable=True))
    op.execute("UPDATE products SET is_approved = FALSE WHERE is_approved IS NULL")
    op.alter_column('products', 'is_approved', nullable=False)
    op.create_index(op.f('ix_products_vendor_id'), 'products', ['vendor_id'], unique=False)
    op.create_foreign_key(None, 'products', 'vendors', ['vendor_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_vendor_id'), table_name='products')
    op.drop_column('products', 'is_approved')
    op.drop_column('products', 'wholesale_price')
    op.drop_column('products', 'vendor_id')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_index(op.f('ix_order_items_vendor_id'), table_name='order_items')
    op.drop_column('order_items', 'wholesale_price_snapshot')
    op.drop_column('order_items', 'vendor_id')
    op.drop_index(op.f('ix_shipments_id'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_vendor_orders_vendor_id'), table_name='vendor_orders')
    op.drop_index(op.f('ix_vendor_orders_status'), table_name='vendor_orders')
    op.drop_index(op.f('ix_vendor_orders_payout_id'), table_name='vendor_orders')
    op.drop_index(op.f('ix_vendor_orders_order_id'), table_name='vendor_orders')
    op.drop_index(op.f('ix_vendor_orders_id'), table_name='vendor_orders')
    op.drop_table('vendor_orders')
    op.drop_index(op.f('ix_inventory_logs_vendor_id'), table_name='inventory_logs')
    op.drop_index(op.f('ix_inventory_logs_product_id'), table_name='inventory_logs')
    op.drop_index(op.f('ix_inventory_logs_id'), table_name='inventory_logs')
    op.drop_table('inventory_logs')
    op.drop_index(op.f('ix_vendor_users_vendor_id'), table_name='vendor_users')
    op.drop_index(op.f('ix_vendor_users_user_id'), table_name='vendor_users')
    op.drop_index(op.f('ix_vendor_users_id'), table_name='vendor_users')
    op.drop_table('vendor_users')
    op.drop_index(op.f('ix_vendor_documents_vendor_id'), table_name='vendor_documents')
    op.drop_index(op.f('ix_vendor_documents_id'), table_name='vendor_documents')
    op.drop_table('vendor_documents')
    op.drop_index(op.f('ix_payouts_vendor_id'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_status'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_id'), table_name='payouts')
    op.drop_table('payouts')
    op.drop_index(op.f('ix_vendors_status'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_id'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_business_email'), table_name='vendors')
    op.drop_table('vendors')
    # ### end Alembic commands ###
